# Generated by Django 6.0.5 on 2026-05-28 00:04

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Category = apps.get_model('catalog', 'Category')
    Product = apps.get_model('catalog', 'Product')

    used_category_slugs = set()
    for category in Category.objects.all().order_by('id'):
        base_slug = slugify(category.name) or f"category-{category.id}"
        slug = base_slug
        counter = 1

        while slug in used_category_slugs or Category.objects.filter(slug=slug).exclude(id=category.id).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1

        category.slug = slug
        category.save(update_fields=['slug'])
        used_category_slugs.add(slug)

    used_product_slugs = set()
    for product in Product.objects.all().order_by('id'):
        base_slug = slugify(product.name) or f"product-{product.id}"
        slug = base_slug
        counter = 1

        while slug in used_product_slugs or Product.objects.filter(slug=slug).exclude(id=product.id).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1

        product.slug = slug
        product.save(update_fields=['slug'])
        used_product_slugs.add(slug)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=80, unique=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=80, unique=True, null=True),
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
    ]

