# Generated by Django 6.0.5 on 2026-05-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sender_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
